Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> Added -V so I could see the error, and it is:
> 
> 16:30:29 2: v_sender.c:48:10: fatal error: rmr/rmr.h: No such file or directory
> 16:30:29 2:  #include <rmr/rmr.h>
> 16:30:29 2:           ^~~~~~~~~~~
> 16:30:29 2: compilation terminated.
> 16:30:29 2: Makefile:69: recipe for target 'v_sender_si' failed
> 16:30:29 2: make[1]: *** [v_sender_si] Error 1
> 
> https://jenkins.o-ran-sc.org/sandbox/view/All/job/ric-plt-lib-rmr-cmake-sonarqube/3/console

Argh!   That's my inability to actually think about what the application tests really need.

They need the dev package, so this line along with the make options:
cmake-opts: -DDEV_PKG=1

Patch-set: 5
Reviewer: Gerrit User 1000037 <1000037@84e4e190-e623-4c37-9eda-58b1937c1b53>